apiVersion: v1
kind: Service
metadata:
  name: backend-servicenodeapi
spec:
  selector:
    app: backendnodeapi
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 32033
      protocol: TCP
  type: NodePort